from typing import Protocol

from .models import ActionReceipt, CapabilityReport, MoveVelocityCommand, RobotState, StandCommand, StopCommand

class R1RobotAdapter(Protocol):
    async def discover_capabilities(self) -> CapabilityReport: ...
    async def get_state(self) -> RobotState: ...
    async def request_stand(self, command: StandCommand) -> ActionReceipt: ...
    async def request_bounded_velocity(self, command: MoveVelocityCommand) -> ActionReceipt: ...
    async def request_stop(self, command: StopCommand) -> ActionReceipt: ...
